import { useState } from 'react';
import { useDataset } from '../context/DatasetContext.jsx';
import { useToast } from '../context/ToastContext.jsx';
import { getExportUrl } from '../api/datasetApi.js';

const API_BASE = import.meta.env.VITE_API_URL || 'http://localhost:3001/api';

function generatePipelineScript(historyItems) {
  const lines = [
    '# DataPrep Pro — Exported Pipeline',
    '# Generated by DataForge Platform',
    '',
    'import pandas as pd',
    'import numpy as np',
    'from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler, LabelEncoder',
    'from sklearn.impute import KNNImputer',
    '# To use IterativeImputer you might need to enable experimental features in older sklearn',
    'try:',
    '    from sklearn.experimental import enable_iterative_imputer',
    'except ImportError: pass',
    'from sklearn.impute import IterativeImputer',
    '',
    'df = pd.read_csv("your_dataset.csv")',
    '',
  ];

  function getMissingLogic(p) {
    if (p.method === 'mean')      return `df['${p.column}'] = df['${p.column}'].fillna(df['${p.column}'].mean())`;
    if (p.method === 'median')    return `df['${p.column}'] = df['${p.column}'].fillna(df['${p.column}'].median())`;
    if (p.method === 'mode')      return `df['${p.column}'] = df['${p.column}'].fillna(df['${p.column}'].mode()[0])`;
    if (p.method === 'knn')       return `df[['${p.column}']] = KNNImputer(n_neighbors=5).fit_transform(df[['${p.column}']])`;
    if (p.method === 'iterative') return `df[['${p.column}']] = IterativeImputer(max_iter=10).fit_transform(df[['${p.column}']])`;
    if (p.method === 'drop_rows') return `df = df.dropna(subset=['${p.column}']).reset_index(drop=True)`;
    if (p.method === 'drop_column') return `df = df.drop(columns=['${p.column}'])`;
    if (p.method === 'custom')     return `df['${p.column}'] = df['${p.column}'].fillna(${JSON.stringify(p.value)})`;
    return `# Unsupported method: ${p.method}`;
  }

  for (const step of historyItems) {
    const p = step.parameters || {};
    const op = step.operation || '';
    lines.push(`# v${step.version}: ${op}`);

    if (op === 'handle_missing') {
      lines.push(getMissingLogic(p));
    } else if (op === 'handle_missing_batch') {
      (p.operations || []).forEach(subOp => {
        lines.push(getMissingLogic(subOp));
      });
    } else if (op === 'remove_duplicates') {
      lines.push('df = df.drop_duplicates().reset_index(drop=True)');
    } else if (op.includes('outliers_iqr')) {
      lines.push(`q1, q3 = df['${p.column}'].quantile([0.25, 0.75]); _iqr = q3 - q1`);
      lines.push(`df = df[(df['${p.column}'] >= q1 - 1.5*_iqr) & (df['${p.column}'] <= q3 + 1.5*_iqr)].reset_index(drop=True)`);
    } else if (op.includes('outliers_zscore')) {
      lines.push(`_z = (df['${p.column}'] - df['${p.column}'].mean()) / df['${p.column}'].std()`);
      lines.push(`df = df[abs(_z) < ${p.threshold || 3}].reset_index(drop=True)`);
    } else if (op.includes('encoding_onehot')) {
      lines.push(`df = pd.get_dummies(df, columns=['${p.column}'], prefix='${p.column}', dtype=int)`);
    } else if (op.includes('encoding_label')) {
      lines.push(`df['${p.column}'] = LabelEncoder().fit_transform(df['${p.column}'].astype(str))`);
    } else if (op.includes('scaling_minmax')) {
      lines.push(`df[${JSON.stringify(p.columns)}] = MinMaxScaler().fit_transform(df[${JSON.stringify(p.columns)}])`);
    } else if (op.includes('scaling_standard')) {
      lines.push(`df[${JSON.stringify(p.columns)}] = StandardScaler().fit_transform(df[${JSON.stringify(p.columns)}])`);
    } else if (op.includes('scaling_robust')) {
      lines.push(`df[${JSON.stringify(p.columns)}] = RobustScaler().fit_transform(df[${JSON.stringify(p.columns)}])`);
    }
    lines.push('');
  }

  lines.push('df.to_csv("cleaned_dataset.csv", index=False)');
  lines.push('print(f"Saved: {len(df)} rows × {len(df.columns)} columns")');
  return lines.join('\n');
}

export default function ExportTab() {
  const { datasetId, currentVersion, shape } = useDataset();
  const { addToast } = useToast();
  const [scriptContent, setScriptContent] = useState('');
  const [scriptReady, setScriptReady] = useState(false);
  const [scriptLoading, setScriptLoading] = useState(false);

  function handleCSVDownload() {
    window.location.href = getExportUrl(datasetId);
    addToast({ type: 'success', title: 'Download started', message: `v${currentVersion} CSV` });
  }

  async function handleGenerateScript() {
    setScriptLoading(true);
    try {
      const res = await fetch(`${API_BASE}/history/${datasetId}`);
      const data = await res.json();
      const script = generatePipelineScript(data.history || []);
      setScriptContent(script);
      setScriptReady(true);
    } catch (err) {
      addToast({ type: 'error', title: 'Failed', message: err.message });
    } finally {
      setScriptLoading(false);
    }
  }

  function handleScriptDownload() {
    const blob = new Blob([scriptContent], { type: 'text/x-python' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `pipeline_${datasetId?.slice(0, 8)}.py`;
    a.click();
    URL.revokeObjectURL(url);
    addToast({ type: 'success', title: 'Script downloaded' });
  }

  return (
    <div className="fade-in">
      {/* Stats */}
      <div className="stat-grid fade-in" style={{ marginBottom: '24px' }}>
        <div className="stat-card amber"><div className="stat-label">Rows</div><div className="stat-value">{shape.rows.toLocaleString()}</div></div>
        <div className="stat-card blue"><div className="stat-label">Columns</div><div className="stat-value blue">{shape.columns}</div></div>
        <div className="stat-card cyan"><div className="stat-label">Version</div><div className="stat-value cyan">v{currentVersion}</div></div>
      </div>

      {/* CSV Export */}
      <div className="card fade-in fade-in-delay-1" style={{ marginBottom: '24px' }}>
        <div className="card-header"><span className="card-title">Export Cleaned Dataset</span></div>
        <div className="card-body" style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '24px', flexWrap: 'wrap' }}>
          <div>
            <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.75rem', color: 'var(--text-secondary)', marginBottom: '8px' }}>
              Downloads current version (v{currentVersion}) as CSV · {shape.rows.toLocaleString()} rows × {shape.columns} columns
            </div>
            <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.65rem', color: 'var(--text-muted)' }}>
              File: <span style={{ color: 'var(--amber)' }}>dataset_{datasetId?.slice(0, 8)}_v{currentVersion}.csv</span>
            </div>
          </div>
          <button className="btn btn-primary btn-lg" onClick={handleCSVDownload}>
            ⬇ Download CSV
          </button>
        </div>
      </div>

      {/* Pipeline Script */}
      <div className="card fade-in fade-in-delay-2">
        <div className="card-header">
          <span className="card-title">Export Pipeline as Python Script</span>
          <div style={{ display: 'flex', gap: '8px' }}>
            <button className="btn btn-secondary btn-sm" onClick={handleGenerateScript} disabled={scriptLoading}>
              {scriptLoading ? <span className="spinner" /> : '⬡'} Generate
            </button>
            {scriptReady && (
              <button className="btn btn-primary btn-sm" onClick={handleScriptDownload}>
                ⬇ Download .py
              </button>
            )}
          </div>
        </div>
        <div className="card-body">
          {scriptReady ? (
            <div className="code-block">{scriptContent}</div>
          ) : (
            <div className="empty-state" style={{ padding: '32px' }}>
              <span className="empty-state-icon" style={{ fontSize: '2rem' }}>⬡</span>
              <span className="empty-state-title">Reproducible Pipeline</span>
              <span className="empty-state-desc">
                Generates a standalone Python script from all your transformation history — ready to apply on any new dataset.
              </span>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
